### PR TITLE
Serve all urls to /index.html if a real file doesn't exist

### PR DESCRIPTION
**Pull request by muffinresearch**
Best not to land this until the react-router patch is done as it modifies the index.html to make this work.

### CODE REVIEW

**Comment by andymckay** [comment]
if its temporary, r+, but not something we want to keep around

**Comment by muffinresearch** [comment]
> if its temporary, r+, but not something we want to keep around

Not sure I understand? This isn't temporary. This is how single page apps work wrt to routing.

**Comment by andymckay** [comment]
That means no matter what URL I try, I won't get a 404, if it doesn't exist I get /index.html?

**Comment by muffinresearch** [comment]
> That means no matter what URL I try, I won't get a 404, if it doesn't exist I get /index.html?

Ah ok, good point - I'll fix it.

**Comment by kumar303** [comment]
I don't understand why this is needed. It doesn't seem to do what the pull request message says, unless I'm just confused.

**Comment by muffinresearch** [comment]
> I don't understand why this is needed. It doesn't seem to do what the pull request message says, unless I'm just confused.

The pull-request was originally using try_files and sending all request to the app. This is of course bad (duh) because it makes getting a 404 impossible. Sadly I didn't update the commit message before I landed it after changing it to be explicitly for the one path we need at the moment. 

I guess this is a downside to using nginx as the sole webserver. Still should only need faily limited urls.

**Pull request merged**
