### PR TITLE
Add source-only FxA storage server (kinto) to docker

### PR DESCRIPTION
**Pull request by kumar303**
Once we have hosted images we can adjust this for the deploy environments.

This gets me:

```
$ curl http://pay.dev:8888/v1/
{"url":"http:\/\/pay.dev:8888\/v1\/","documentation":"https:\/\/kinto.rtfd.org\/","version":"1.0.0.dev0","hello":"cloud storage"}
```

### CODE REVIEW

**Comment by muffinresearch** [comment]
r+

**Comment by andymckay** [comment]
Could this be moved into configs and use extends so we can use it in -deploy as well?

**Comment by kumar303** [comment]
it won't work in deploy yet because there isn't a hosted image. I'm filing an issue for that now so we can fix it up.

**Comment by kumar303** [comment]
Filed https://github.com/mozilla-services/kinto/issues/55

**Pull request merged**
